### ISSUE TITLE
Could not launch again on the first day

### ISSUE THREAD

**Issue by protist** [jclehner/rxdroid#31]
I installed this yesterday, added a drug, then quit. I couldn't launch the app again. Every time I attempted, it immediately crashed. I could tell the app was still running, because there was a notification saying I was running low on supply for my drug. I just couldn't launch the app manually. [Here](https://del.dog/awiqappamu.txt) is the error.

Oddly enough, when I attempted today, it launched fine, so perhaps it was just an error on the first day.

RxDroid 0.9.33.2, DB v60, installed from F-Droid
Moto G6 Plus
Android 9 (ResurrectionRemix)

**Comment by crapforge** [comment]
It's been a while since this comment, but I can confirm the issue.

LineageOS 18.1 on a Xiaomi Redmi Note 8T

RXDroid shows the following behaviour:

1. Fresh install: exits immediately after starting
2. Then cleared cache and data in Settings/Apps: RXDroid actually starts and let's me enter my medication.
3. Any further attempts to start the app result in it immediately exiting again. It is not possible to change anything "inside" the app.
4. Notifications interestingly still work.

Any help? Or how can I help to help troubleshoot this issue?

**Comment by jclehner** [comment]
Does the attached version fix your issue? Note that you'll have to extract the `.zip` file first, because GitHub won't allow `.apk` files as attachments.

[RxDroid-0.9.34.1.zip](https://github.com/jclehner/rxdroid/files/6665005/RxDroid-0.9.34.1.zip)

**Comment by crapforge** [comment]
Yes, it does. 

Seems to work fine now. Thanks!

**Comment by protist** [comment]
I tried clearing all my data to test this. Before installing the new apk, I tried to replicate the original issue as a control, but I couldn't make it crash any more! Unfortunately without that replication, I wouldn't be able to show there was any difference, so I'm not in a position to confirm if the fix works or not. @crapforge's comment is hopefully enough confirmation. Thank you for the fix though.

**Comment by jclehner** [comment]
@protist I couldn't replicate this crash either, neither on my phone, nor in the Android emulator. However, from the sequence of events that led to it, it most likely was the same issue as @crapforge's!

I've just released 0.9.34.2, which should fix this.

**Comment by protist** [comment]
Thanks @jclehner!
