### ISSUE TITLE
Fdroid submission?

### ISSUE THREAD

**Issue by rsw0x** [jclehner/rxdroid#4]
Hi,
Have you considered submitting this to [Fdroid](https://f-droid.org/) at all?
Fdroid is a repository similar to the Google Store for FOSS-only android software.

Thanks for the great app.

**Comment by ghost** [comment]
We received a submission at https://gitlab.com/fdroid/fdroiddata/merge_requests/2173, so it would be good to know if you object to it being added.

Also, what's the reason/difference for your local .m2 repo to upstream sources?

**Comment by jclehner** [comment]
I don't object to it at all, no. The NumberPicker and ShowcaseView libraries found in the local .m2 repo were modified to suit the needs of this program, but only ShowcaseView is still being used by the current version. 

As you can tell by the commit history, this project is unfortunately almost dead, since I don't have the time and motivation for the extensive overhaul that the code needs in my opinion, so don't expect much more than bugfixes.

**Comment by k3a** [comment]
I fear the Fdroid submission is still blocked by the modified ShowCaseView. Could it be replaced by https://github.com/deano2390/MaterialShowcaseView for example eventually?
